# Generated by Django 4.2.5 on 2023-09-24 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailform',
            name='Age',
            field=models.CharField(max_length=255),
        ),
    ]
