# Generated by Django 4.2.5 on 2023-09-24 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail_app', '0002_alter_mailform_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailform',
            name='Age',
            field=models.IntegerField(),
        ),
    ]
